export const genresDB = {
    1: { uk: "Соціальна дедукція", en: "Social Deduction", ru: "Социальная дедукция" },
    2: { uk: "MOBA", en: "MOBA", ru: "MOBA" },
    3: { uk: "РПГ", en: "RPG", ru: "РПГ" },
    4: { uk: "Королівська битва", en: "Battle Royale", ru: "Королевская битва" },
    5: { uk: "Шутер", en: "Shooter", ru: "Шутер" },
    6: { uk: "Пісочниця", en: "Sandbox", ru: "Песочница" },
    7: { uk: "Екшн", en: "Action", ru: "Экшн" },
    8: { uk: "Пригоди", en: "Adventure", ru: "Приключения" },
    9: { uk: "Симулятор", en: "Simulator", ru: "Симулятор" },
    10: { uk: "Платформер", en: "Platformer", ru: "Платформер" },
    11: { uk: "Виживання", en: "Survival", ru: "Выживание" },
    12: { uk: "Перегони", en: "Racing", ru: "Гонки" },
    13: { uk: "Роуглайк", en: "Roguelike", ru: "Роуглайк" },
    14: { uk: "Космос", en: "Space", ru: "Космос" },
    15: { uk: "Наукова фантастика", en: "Sci-Fi", ru: "Научная фантастика" },
    16: { uk: "Відкритий світ", en: "Open World", ru: "Открытый мир" },
    17: { uk: "Інді", en: "Indie", ru: "Инди" },
    18: { uk: "Стратегія", en: "Strategy", ru: "Стратегия" },
    19: { uk: "Стелс", en: "Stealth", ru: "Стелс" }
};