export const translations = {
  uk: {
    // ... (попередні переклади) ...
    "nav.auth_manage": "Керування акаунтом",
    "nav.signin": "Вхід",
    "nav.signup": "Реєстрація",
    "nav.menu_title": "Меню розділів",
    "nav.home": "Головна",
    "nav.favorites": "Обране",
    "nav.lang": "Змінити мову (UK)",
    "nav.contacts": "Контакти",
    "nav.about": "Про проєкт",
    "nav.logout": "Вийти",
    "nav.welcome": "Вітаємо,",
    "header.tagline": "Каталог ігор та спільнота геймерів",
    "header.pulse": "Разом граємо",
    "search.placeholder": "Пошук ігор...",
    "search.btn": "Знайти",
    "search.not_found": "Нічого не знайдено за запитом",
    "catalog.title": "Каталог ігор",
    "catalog.desc": "Переглядайте добірки проєктів...",
    "fav.title": "Ваші обрані ігри ❤️",
    "fav.desc": "Тут зібрані всі ігри, які ви відзначили серцем.",
    "fav.empty": "Ви ще не додали ігор до обраного.",
    "fav.goto": "Перейти до каталогу",
    "fav.login_req": "Будь ласка, увійдіть в акаунт.",
    "footer.connect": "Ми на зв'язку",
    "footer.copyright": "© 2025 GameHub.",
    "modal.login.title": "Вхід до акаунта",
    "modal.login.btn": "Увійти",
    "modal.no_account": "Немає акаунта?",
    "modal.register.title": "Створення акаунта",
    "modal.register.btn": "Створити акаунт",
    "modal.has_account": "Вже маєте акаунт?",
    "modal.placeholder.login": "Логін",
    "modal.placeholder.pass": "Пароль",
    "modal.placeholder.pass_confirm": "Підтвердьте пароль",
    "modal.success_reg": "Реєстрація успішна!",
    "modal.welcome": "Ласкаво просимо,",
    "contacts.title": "Зв’яжись із нашою командою 🎮",
    "contacts.desc": "Ми завжди відкриті до спілкування!",
    "contacts.find_us": "Як нас знайти",
    "contacts.email": "Email:",
    "contacts.phone": "Телефон:",
    "contacts.office": "Офіс:",
    "contacts.form_title": "Форма зворотного зв’язку",
    "contacts.label_name": "Ім’я",
    "contacts.label_email": "Email",
    "contacts.label_subject": "Тема",
    "contacts.label_message": "Повідомлення",
    "contacts.btn_send": "Надіслати",
    "about.title": "Про проєкт GameHub",
    "about.desc": "Платформа для геймерів.",
    "about.mission_title": "Наше призначення",
    "about.mission_desc": "Об’єднати шанувальників відеоігор.",
    "about.team_title": "Команда",
    "about.team_desc": "Створено ентузіастами.",
    "game.genre": "Жанр:",
    "game.rating": "Рейтинг:",
    "game.reviews_title": "Відгуки гравців",
    "game.no_reviews": "Поки що немає відгуків. Будьте першим!",
    "game.desc_empty": "Опис для цієї гри готується.",
    "game.form.label": "Залишити відгук",
    "game.form.placeholder": "Ваші враження...",
    "game.form.btn": "Опублікувати",
    "game.form.login_req": "Увійдіть, щоб залишити відгук",
    "game.form.already": "Ви вже залишили відгук до цієї гри.",
    "game.rating.na": "Немає оцінок",

    // === СПОВІЩЕННЯ (NOTIFICATIONS) ===
    "notify.pass_mismatch": "Паролі не збігаються.",
    "notify.reg_error": "Помилка реєстрації.",
    "notify.login_error": "Помилка авторизації.",
    "notify.server_error": "Помилка сервера.",
    "notify.logout": "Ви вийшли з акаунта.",
    "notify.rating_req": "Будь ласка, поставте оцінку!",
    "notify.review_success": "Відгук успішно додано!",
    "notify.error": "Сталася помилка."
  },

  en: {
    // ...
    "nav.auth_manage": "Account Management",
    "nav.signin": "Sign In",
    "nav.signup": "Sign Up",
    "nav.menu_title": "Menu",
    "nav.home": "Home",
    "nav.favorites": "Favorites",
    "nav.lang": "Change Language (EN)",
    "nav.contacts": "Contacts",
    "nav.about": "About Us",
    "nav.logout": "Logout",
    "nav.welcome": "Welcome,",
    "header.tagline": "Game catalog & community",
    "header.pulse": "Let's Play",
    "search.placeholder": "Search games...",
    "search.btn": "Search",
    "search.not_found": "Nothing found for",
    "catalog.title": "Game Catalog",
    "catalog.desc": "Browse game collections...",
    "fav.title": "Your Favorite Games ❤️",
    "fav.desc": "Here are all the games you marked.",
    "fav.empty": "No favorites yet.",
    "fav.goto": "Go to catalog",
    "fav.login_req": "Please sign in.",
    "footer.connect": "Contact Us",
    "footer.copyright": "© 2025 GameHub.",
    "modal.login.title": "Sign In",
    "modal.login.btn": "Login",
    "modal.no_account": "No account?",
    "modal.register.title": "Create Account",
    "modal.register.btn": "Register",
    "modal.has_account": "Already have an account?",
    "modal.placeholder.login": "Login",
    "modal.placeholder.pass": "Password",
    "modal.placeholder.pass_confirm": "Confirm Password",
    "modal.success_reg": "Registration successful!",
    "modal.welcome": "Welcome,",
    "contacts.title": "Contact our team 🎮",
    "contacts.desc": "We are always open to chat!",
    "contacts.find_us": "How to find us",
    "contacts.email": "Email:",
    "contacts.phone": "Phone:",
    "contacts.office": "Office:",
    "contacts.form_title": "Feedback Form",
    "contacts.label_name": "Name",
    "contacts.label_email": "Email",
    "contacts.label_subject": "Subject",
    "contacts.label_message": "Message",
    "contacts.btn_send": "Send Message",
    "about.title": "About GameHub",
    "about.desc": "Platform for gamers.",
    "about.mission_title": "Our Mission",
    "about.mission_desc": "Unite video game fans.",
    "about.team_title": "Team",
    "about.team_desc": "Created by enthusiasts.",
    "game.genre": "Genre:",
    "game.rating": "Rating:",
    "game.reviews_title": "User Reviews",
    "game.no_reviews": "No reviews yet. Be the first!",
    "game.desc_empty": "Description coming soon.",
    "game.form.label": "Leave a review",
    "game.form.placeholder": "Your thoughts...",
    "game.form.btn": "Publish",
    "game.form.login_req": "Login to review",
    "game.form.already": "You have already reviewed this game.",
    "game.rating.na": "No ratings",

    // === NOTIFICATIONS ===
    "notify.pass_mismatch": "Passwords do not match.",
    "notify.reg_error": "Registration failed.",
    "notify.login_error": "Login failed.",
    "notify.server_error": "Server error.",
    "notify.logout": "You have logged out.",
    "notify.rating_req": "Please select a rating!",
    "notify.review_success": "Review added successfully!",
    "notify.error": "An error occurred."
  },

  ru: {
    // ...
    "nav.auth_manage": "Управление",
    "nav.signin": "Войти",
    "nav.signup": "Регистрация",
    "nav.menu_title": "Меню",
    "nav.home": "Главная",
    "nav.favorites": "Избранное",
    "nav.lang": "Сменить язык (RU)",
    "nav.contacts": "Контакты",
    "nav.about": "О проекте",
    "nav.logout": "Выйти",
    "nav.welcome": "Привет,",
    "header.tagline": "Каталог игр и сообщество",
    "header.pulse": "Играем вместе",
    "search.placeholder": "Поиск игр...",
    "search.btn": "Найти",
    "search.not_found": "Ничего не найдено",
    "catalog.title": "Каталог игр",
    "catalog.desc": "Просматривайте подборки...",
    "fav.title": "Ваши любимые игры ❤️",
    "fav.desc": "Здесь собраны все игры...",
    "fav.empty": "Вы еще не добавили игры.",
    "fav.goto": "Перейти в каталог",
    "fav.login_req": "Пожалуйста, войдите.",
    "footer.connect": "Мы на связи",
    "footer.copyright": "© 2025 GameHub.",
    "modal.login.title": "Вход в аккаунт",
    "modal.login.btn": "Войти",
    "modal.no_account": "Нет аккаунта?",
    "modal.register.title": "Создание аккаунта",
    "modal.register.btn": "Создать аккаунт",
    "modal.has_account": "Уже есть аккаунт?",
    "modal.placeholder.login": "Логин",
    "modal.placeholder.pass": "Пароль",
    "modal.placeholder.pass_confirm": "Подтвердите пароль",
    "modal.success_reg": "Регистрация успешна!",
    "modal.welcome": "Добро пожаловать,",
    "contacts.title": "Свяжитесь с нами 🎮",
    "contacts.desc": "Мы всегда открыты к общению!",
    "contacts.find_us": "Как нас найти",
    "contacts.email": "Email:",
    "contacts.phone": "Телефон:",
    "contacts.office": "Офис:",
    "contacts.form_title": "Форма связи",
    "contacts.label_name": "Имя",
    "contacts.label_email": "Email",
    "contacts.label_subject": "Тема",
    "contacts.label_message": "Сообщение",
    "contacts.btn_send": "Отправить",
    "about.title": "О проекте GameHub",
    "about.desc": "Платформа для геймеров.",
    "about.mission_title": "Наше предназначение",
    "about.mission_desc": "Объединить поклонников игр.",
    "about.team_title": "Команда",
    "about.team_desc": "Создано энтузиастами.",
    "game.genre": "Жанр:",
    "game.rating": "Рейтинг:",
    "game.reviews_title": "Отзывы игроков",
    "game.no_reviews": "Отзывов пока нет. Будьте первым!",
    "game.desc_empty": "Описание готовится.",
    "game.form.label": "Оставить отзыв",
    "game.form.placeholder": "Ваши впечатления...",
    "game.form.btn": "Опубликовать",
    "game.form.login_req": "Войдите, чтобы оставить отзыв",
    "game.form.already": "Вы уже оставили отзыв к этой игре.",
    "game.rating.na": "Нет оценок",

    // === NOTIFICATIONS ===
    "notify.pass_mismatch": "Пароли не совпадают.",
    "notify.reg_error": "Ошибка регистрации.",
    "notify.login_error": "Ошибка авторизации.",
    "notify.server_error": "Ошибка сервера.",
    "notify.logout": "Вы вышли из аккаунта.",
    "notify.rating_req": "Пожалуйста, поставьте оценку!",
    "notify.review_success": "Отзыв успешно добавлен!",
    "notify.error": "Произошла ошибка."
  }
};